services:
  tmdb-nfo:
    build: .
    container_name: emby-nfo-generator
    volumes:
      - ./app/config.ini:/app/config.ini           # 挂载配置文件
      - ./app/media:/app/media                     # 挂载媒体目录（可改）
      - ./logs:/app                                # 挂载日志与输出
    restart: "no"
